name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"


- name: Android CI/CD

  uses: henriquehorbovyi/Android-CI-CD@v0.0.1-beta5


- name: Install Dependencies

  run: npm install
	
	
	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	

	
